### ISSUE TITLE
It would be good to get the full dot path of a cfc

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-lucee#15]
A simple way to get the path of the current cfc would be great so for example if I am in 

    /project/cfcs/model/user/UserService.cfc

Then being able to (somehow) get the path as 

    cfcs.model.user.UserService

would be a very handy way to do this.

**Comment by jcberquist** [comment]
Hi again :). First, this is off topic, but are you using the `.lucee` syntax with this package, or are you only using this for the CFML syntax? I ask because I think for now I am going to focus on the other repository which is focused more generically on CFML (I realized that I have a number of users that use this with ColdFusion), and then decide what to do here when the Lucee 5 dialect is out of development, so to speak. The only thing here that is not in the sublimetext-cfml repo is really the Lucee syntax itself, and the CFML syntax is a little bit more up to date over there.

More on topic, what you are saying sounds interesting, but I am not sure I grasp the context. Where would you like to get the path to the current cfc? What would the user/plugin be doing when they wanted to get the path?

**Comment by cybersonic** [comment]
Hey there
Ahh, that makes sense, I shall switch to that repo if needed. I am actually doing lucee development but with .cfc/.cfm rather than .lucee 

The context would be pretty simple actually, if you have ever tried https://github.com/titoBouzout/SideBarEnhancements you see that you can right click on a file and get the path as text. "Copy Path" but there are a bunch of other ways to copy the path (not what I meant) but just need to get the path dot notated up to the project. Pretty simple. I wouldn't go much further (as it can get super complicated) but it would help for 90% of cases

<img width="510" alt="screen shot 2016-01-06 at 14 39 01" src="https://cloud.githubusercontent.com/assets/148252/12144992/4e7a6012-b483-11e5-9b51-8fe5f25494d5.png">

**Comment by jcberquist** [comment]
Very cool, I haven't actually used that package, but what you are asking for seems very doable to me. Are you thinking of an integration where you right click on the side bar, or on the file itself, or both?

**Comment by jcberquist** [comment]
I have pushed a commit to the sublimetext-cfml repository that addresses this issue, at least on a basic level. I also added a note to this repository recommending folks switch to the other repo, unless they are specifically looking for `.lucee` syntax highlighting. Let me know what you think.

**Comment by jcberquist** [comment]
I wonder if it would make sense to let users define base paths to cfc folders in the project settings file (I am thinking that these would correspond to mappings in App.cfc or the admin), and the command could just look for the base path that matches the path to the cfc that has been right-clicked on, strip out that base path, and then convert the remainder to a dotted path. The project folders themselves would still be used as a fallback if no such folders were defined.

**Comment by cybersonic** [comment]
I shall switch over to that repo today and check it out. 

If you do a settings file it might be useful. When I did this for CFEclipse, mappings are a real problem. Take the following CFC (actual path) 

    /libs/testbox/system/TestBox.cfc

if you have two mappings:

`/libs -> /libs`

`/testbox` -> `/libs/testbox`

if you try and find the TestBox.cfc you can do:

`new libs.testbox.system.TestBox();`

which is just as valid as 

`new testbox.system.TestBox()`

as this is a forward search. If you are going backwards from the TestBox.cfc  to the root I am not sure what rules you could apply first? First match in the mappings? Last match?

Whichever way (I am presuming a loop over the mapping paths) as long as it is consistent and you can override it by changing the order it would be fine. 

Does this make sense?

**Comment by jcberquist** [comment]
Yes, I think I follow. I would be inclined to follow the rule that first match wins, and have mappings defined in an array. Then as you say, the user could control which mapping is used. 

With regard to adding dot completions after typing `new` I don't think the order would matter, as it would just depend on what is typed first. I will look into that.

Have you tried out the model completions feature that you can enable in a project? I made it to work with singletons from DI/1 in a FW/1 project (which I think you use, at least some of the time?). I would love to make that more robust, but I think I may be the only one using it. For instance, it doesn't currently handle completions for a cfc that come from a base cfc that the cfc extends. It comes to mind with this talk of mappings, since I would need a way to sort out dotted paths in the `extends` in order to find the base cfc and index it.

**Comment by cybersonic** [comment]
I havent tried the model completions feature yet. I saw it was there but my project structure is using sub systems so it's more along the lines of:

    www
    ├── model
    │   ├── beans
    │   ├── interceptors
    │   └── services
    ├── public
    │   ├── subsystems
    │   │   ├── common
    │   │   │   ├── layouts
    │   │   ├── dashboard
    │   │   │   ├── controllers
    │   │   │   └── views
    │   │   │       └── main
    │   │   ├── public
    │   │   │   ├── controllers
    │   │   │   └── views
    │   │   │       ├── auth
    │   │   │       ├── main
    │   │   │       ├── resetPassword

Which I am not sure how that helps. With regards to extednds... sometimes being less clever is better, having a way to have ALL the methods available is good sometimes... otherwise you have to put lucee or commandbox and use a lot of componentMetaData() calls.

**Comment by cybersonic** [comment]
Holy Bat-socks Batman! The cmd + F1 is incredible! you have just saved me a whole day's worth of switching!

**Comment by cybersonic** [comment]
I tried the completions... although I can't get it to work. The docs say:

> To set this up you add the following setting to your project file: "model_completion_folders": [ "/full/path/to/model", "/another/full/path/to/index" ].

The full path would it be from the project? and does it recurse? A lot of my services are under their own folders for example `/model/services/search/SearchService.cfc` or  `/model/services/user/UserService.cfc`

Would the paths to be this be:

`"model_completion_folders": [ "/model/services","/services/search"],`
or 

`"model_completion_folders": [ "/Users/markdrew/Sites/project/model/services","/Users/markdrew/Sites/project/model/services/search"],`

**Comment by jcberquist** [comment]
Glad you like controller-view toggle command, I do too :).

The idea with the model completions is supposed to be that you give it absolute paths to the same folders DI/1 is indexing via `diLocations` in `variables.framework`. It recurses through those directories and indexes all cfcs, mapping them to a dict via the cfc name, and then the cfc name + containing folder (like DI/1). It is supposed to then offer the functions of those cfcs as completions if you type the cfc name (or alias) and then `.`.

So, for example if you have:
```
model
|-- services
    |-- user.cfc
    |-- mailService.cfc
```
and you supply the model folder as an absolute path to the `"model_completion_folders"` setting in the project file, then if you type any of the following (no matter where in the project, I don't check for `property` settings): `userService,user,mailService,mailServiceService` and follow with a `.` it should offer those cfcs' methods as completions.

**Comment by cybersonic** [comment]
again, when you say an absolute path you mean from my machine's root right?

**Comment by jcberquist** [comment]
Yes, that's exactly right.

**Comment by cybersonic** [comment]
And this would be in a `project.sublime_project` file that I have put in the root of my project?

**Comment by jcberquist** [comment]
Yes, so in the menu it would be the file you get to via `Project -> Edit Project` or from the command palate (`CMD+SHIFT+P` on a Mac I think), via `Project: Edit Project`.

**Comment by cybersonic** [comment]
Ahh! It hadn't converted it to a project! Now that is pretty epic! 
thank you sah!

**Comment by cybersonic** [comment]
(as an aside, in ST3 projects are a little funky)

**Comment by cybersonic** [comment]
As a note, you might also want to add get<ServiceName>. to the list of triggers.  we inject our services via properties like :

    component accessors="true" {
    
    	property name =	"SearchService"			setter="true" 	getter="true";
    
    	function default(rc){
    
    		getSearchService().findByString(rc.term);
    
    	}
    
    }


so the function `getSearchService().` should trigger the functions in the search service... if that can be done?

**Comment by jcberquist** [comment]
Yes, I can add that. My goal is to provide more completions than are necessary rather then less, so I prefer false positives to not offering completions at all.

Since you are using FW/1 you might want to add `"fw1_enabled": true` to your project file as well. It will add completions for `framework.` in controller files (though perhaps you will run into the same problem you mention there as well, do you do `getFramework()` in controllers?), and the same completions in `Application.cfc` and view files without the prefix. (So things like `framework.setView()` or `framework.redirect()`, etc. I also inline the FW/1 docs so if you press F1 on any of those methods you will get the FW/1 docs for them. It will also add FW/1 `variables.framework` completions in `Application.cfc` as well as the docs for the same.

**Comment by cybersonic** [comment]
I just enabled it and it works a treat (although in this project we are not doing them directly) we still use fw.something() so it's epic! Thanks for this great project!

**Comment by jcberquist** [comment]
Thanks, Mark, I appreciate it, and I am glad you find the project useful.

I have updated the model completions (in sublimetext-cfml) to also work with property getters. I also added getter and setter completions in cfcs. It finds all property names in the cfc and offers a getter and setter for each one, no matter what your accessor settings are - like I said, my thinking is that I would rather offer more completions than less. Though down the road this could probably be easily refined.

**Comment by cybersonic** [comment]
Is this in this repository or the https://github.com/jcberquist/sublimetext-cfml one?

**Comment by jcberquist** [comment]
It is in the other repository (https://github.com/jcberquist/sublimetext-cfml). For now, that is where I plan on updating things.

**Comment by jcberquist** [comment]
I am not sure what the status of this ticket is? I am going to close it, but as I do, I will ask: have you tried out any of the TestBox functionality? I think the instructions need improvement, so I am interesting in finding out if you were able to get that to work.
