### ISSUE TITLE
Constructive criticism

### ISSUE THREAD

**Issue by ghedwards** [jcberquist/sublimetext-lucee#8]
To whom it may concern,

I was excited by the prospect of another CFML / Lucee editor for sublimetext so I jumped right in, I had a couple of teething issues switching to this version over the dev version of the ColdFusion sublime plugin, but these appeared to be associated with some sort of sublime plugin caching. 

Unfortunately this version doesn't quite hit the mark as yet and I have since switched back to the ColdFusion sublime plugin, here are a couple of items that caused me to switch back, maybe something I did wrong?

- Syntax highlighting, while this was good it stopped highlighting scopes such as ARGUMENTS and VARIABLES separately to the rest of the statement.

- Context help no longer matched existing arbitrary strings or variables within the same template? i.e. if I have used a variable before, it appears in the type context for use again, so I don't have to type the whole variable again.

Happy to answer any questions and / or do some further testing in the future.

**Comment by jcberquist** [comment]
Hi, thanks for trying the plugin out. Regarding your issues:
- I am not sure if I follow what you mean by "it stopped highlighting scopes such as ARGUMENTS and VARIABLES separately to the rest of the statement"? Do you mean that when you type `arguments.foo` that `arguments` isn't a different color than `foo`? Could you provide a specific example? It would also be helpful to know what color scheme you use, since highlighting will vary between different color schemes.
- By context help do you mean the auto suggest completions that are offered as you type? If I understand you correctly you are saying that variable names that you have already used are not offered to you as completion options later on in the same file. If that is what you mean, the behavior you see is caused by the plugin, as I currently have the plugin generated suggestions inhibiting Sublime's own suggestions. I hadn't noticed it, because I use the `AllAutocomplete` plugin and so I get them anyways. But I tried disabling that, and I see that no other suggestions are offered. Thanks for pointing that out, it is probably a good idea to change that behavior.

**Comment by ghedwards** [comment]
- Yes, the arguments.foo reference is a perfect example, I'm using Materialize Monokai.
- Yes, it would be good to have this behaviour.

**Comment by jcberquist** [comment]
I have updated the completion behavior. Again, thanks for pointing that out.

I also looked into the scope highlighting issue. The ColdFusion package marks scopes such as `arguments` as `variable.language.cfscript` while this package marks them as `variable.language.scope.cfml`. That isn't going to make a difference in any color scheme as they will never style beyond `variable.language`. What is actually happening, I think, is that you are typing the scopes in all uppercase (e.g. `ARGUMENTS`, as you first typed it in the issue), and the ColdFusion package marks any all-uppercase variable as `constant.other.cfscript`. The order of the syntax matches in the package means that `ARGUMENTS` is matched as a constant before it can be matched as a scope, and then you are seeing the Monokai styling for constants. 

Monokai does not have a distinct style for `variable.language` so when using this package (or the ColdFusion one, if you do not uppercase the scope), you will not see the scope colored differently. Other color schemes do offer distinct styling for `variable.language` and then you will see the scope style stand out. (Oceanic Next is the color scheme I am currently using and is an example of this.)

Given that I actually follow the ColdFusion package in how it marks CFML scopes, and that, if you want to use this package, you could either use a different color scheme or add a `variable.language` style to your current color scheme to get the styling you want, I am not inclined to change this.
